/* Auto-generated from tools/schema/schema_map.sql — do not edit. */
#include <stddef.h>

const char webmap_schema_map_sql[] =
    "-- Map feature tables (data only — no display policy).\n"
    "-- Rows are mappable geometry + attributes. Style/tessellation lives in the host\n"
    "-- (demo/display/) or an optional bake step.\n"
    "--\n"
    "-- Populated by fiber2features from fiber_design.sqlite (or written as\n"
    "-- OUT/features.sqlite alongside .fmap tiles).\n"
    "\n"
    "PRAGMA foreign_keys = ON;\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS map_meta (\n"
    "  key   TEXT PRIMARY KEY,\n"
    "  value TEXT\n"
    ");\n"
    "\n"
    "-- Cable / drop spans for the map (WGS84 line coordinates stored as WKB).\n"
    "CREATE TABLE IF NOT EXISTS map_cables (\n"
    "  id            INTEGER PRIMARY KEY,\n"
    "  guid          TEXT,\n"
    "  is_drop       INTEGER NOT NULL DEFAULT 0,\n"
    "  cable_size    INTEGER,\n"
    "  strand_color  TEXT,          -- TIA name (data attribute)\n"
    "  tube_color    TEXT,\n"
    "  rgba          INTEGER,       -- packed 0xAABBGGRR convenience color\n"
    "  geom_wgs84    BLOB           -- WKB LineString (lon/lat), optional\n"
    ");\n"
    "\n"
    "CREATE INDEX IF NOT EXISTS map_cables_drop_idx ON map_cables(is_drop);\n"
    "\n"
    "-- Tap nodes: one row per tap equipment feature.\n"
    "CREATE TABLE IF NOT EXISTS map_taps (\n"
    "  id            INTEGER PRIMARY KEY,\n"
    "  equip_guid    TEXT,\n"
    "  sp_guid       TEXT,          -- splicepoint GUID (for diagram link)\n"
    "  lon           REAL NOT NULL,\n"
    "  lat           REAL NOT NULL,\n"
    "  ports         INTEGER NOT NULL,  -- drop port count (first-class column)\n"
    "  strand_color  TEXT,\n"
    "  tube_color    TEXT,\n"
    "  strand_rgba   INTEGER,\n"
    "  tube_rgba     INTEGER,\n"
    "  diagram       TEXT           -- HTML basename under splice_diagrams/\n"
    ");\n"
    "\n"
    "CREATE INDEX IF NOT EXISTS map_taps_lonlat ON map_taps(lon, lat);\n"
    "\n"
    "-- Non-tap splicepoints (no tap equipment at the SP).\n"
    "CREATE TABLE IF NOT EXISTS map_splices (\n"
    "  id            INTEGER PRIMARY KEY,\n"
    "  sp_guid       TEXT,\n"
    "  lon           REAL NOT NULL,\n"
    "  lat           REAL NOT NULL,\n"
    "  station_id    TEXT,\n"
    "  rgba          INTEGER,\n"
    "  diagram       TEXT           -- HTML basename under splice_diagrams/\n"
    ");\n"
    "\n"
    "CREATE INDEX IF NOT EXISTS map_splices_lonlat ON map_splices(lon, lat);\n"
;
const size_t webmap_schema_map_sql_len = sizeof(webmap_schema_map_sql) - 1;

