# Stage large/regenerable demo package trees into build/demo.
# Prefer a symlink to the source tree (cheap, always current) over copying GB
# of HTML/JSON. Falls back to skip if the source path is missing.

function(webmap_link_or_skip src_name)
  set(_src "${DEMO_SRC}/${src_name}")
  set(_dst "${DEMO_DST}/${src_name}")
  if(NOT EXISTS "${_src}")
    message(STATUS "demo: skip ${src_name} (not present under source demo/)")
    return()
  endif()
  # Replace stale copy or broken link
  if(EXISTS "${_dst}" OR IS_SYMLINK "${_dst}")
    file(REMOVE_RECURSE "${_dst}")
  endif()
  file(CREATE_LINK "${_src}" "${_dst}" SYMBOLIC)
  message(STATUS "demo: ${_dst} → ${_src}")
endfunction()

# Packages / trees that are large or regenerated by bake tools
webmap_link_or_skip("basemap")
webmap_link_or_skip("fiber_data")
webmap_link_or_skip("splice_diagrams")
webmap_link_or_skip("tiles_fiber")

# Optional WASM module if present next to sources or already built
foreach(_wasm "webmap.wasm")
  if(EXISTS "${DEMO_SRC}/${_wasm}")
    file(COPY "${DEMO_SRC}/${_wasm}" DESTINATION "${DEMO_DST}")
  elseif(EXISTS "${CMAKE_BINARY_DIR}/${_wasm}")
    file(COPY "${CMAKE_BINARY_DIR}/${_wasm}" DESTINATION "${DEMO_DST}")
  endif()
endforeach()
